version: '3'
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env  # Specify the path to your .env file here
    environment:
      - NODE_ENV=development
      # Add other environment variables as needed for Prisma configuration
    depends_on:
      - database
      - mailhog

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025" # Mailhog web UI

  database:
    image: prismagraphql/prisma
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

